/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;



import javax.swing.RowFilter;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import java.awt.Dimension;
import java.awt.Rectangle;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Fahri Hanif
 */
public class vKonsultan extends javax.swing.JDialog {

    //Controller_Konsultan controlSql1_Pengguna = new Controller_Konsultan();
    DefaultTableModel model = new DefaultTableModel();

    //ControllerTBL_Konsultan controlTabel1_pengguna = new ControllerTBL_Konsultan();
    private TableRowSorter<TableModel> sorter;

    /**
     * Creates new form vKonsultan
     */
    public vKonsultan(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Model.Koneksi.koneksi();
        headerTable();
        tampilKonsultan();
        aturTombol(false);
        bersih();
        kode();

        Dimension dim = getToolkit().getScreenSize();
        Rectangle abounds = getBounds();
        setLocation((dim.width - abounds.width) / 2, (dim.height - abounds.height) / 4);
        //test

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfNama = new javax.swing.JTextField();
        tfJabatan = new javax.swing.JTextField();
        tfGolongan = new javax.swing.JTextField();
        btnBaru = new javax.swing.JButton();
        btnEdit = new javax.swing.JButton();
        btnHapus = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        tfTingkat = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tfKode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Data Konsultan");

        jLabel2.setText("Nama");

        jLabel3.setText("Jabatan");

        jLabel4.setText("Golongan");

        tfNama.setText("jTextField1");

        tfJabatan.setText("jTextField2");

        tfGolongan.setText("jTextField3");

        btnBaru.setText("Baru");
        btnBaru.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBaruActionPerformed(evt);
            }
        });

        btnEdit.setText("Edit");
        btnEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        jLabel5.setText("Tingkat");

        tfTingkat.setText("jTextField3");

        jLabel6.setText("Kode");

        tfKode.setText("jTextField1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(131, 131, 131)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5))
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfNama)
                            .addComponent(tfJabatan)
                            .addComponent(tfGolongan)
                            .addComponent(tfTingkat, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(tfKode, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfKode, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tfNama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(tfJabatan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(tfGolongan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(tfTingkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnBaru, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEdit, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnHapus, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSimpan, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        int row = jTable1.getSelectedRow();
        if (jTable1.getSelectedColumnCount() == 1) {
            tfKode.setText(jTable1.getValueAt(row, 0).toString());
            tfNama.setText(jTable1.getValueAt(row, 1).toString());
            tfJabatan.setText(jTable1.getValueAt(row, 2).toString());
            tfGolongan.setText(jTable1.getValueAt(row, 3).toString());
            tfTingkat.setText(jTable1.getValueAt(row, 4).toString());
            btnBaru.setEnabled(true);
            btnEdit.setEnabled(true);
            btnHapus.setEnabled(true);
            btnSimpan.setEnabled(false);
            //jTextField5_Password.setText(jTable1.getValueAt(row, 4).toString());
        }       // TODO add your handling code here:
    }//GEN-LAST:event_jTable1MouseClicked

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
        try {
            if (tfGolongan.getText().equals(null) || tfTingkat.getText().equals(null)) {
                tfGolongan.setText("-");
                tfTingkat.setText("-");
            }
            if (cekData() == true) {
                Model.Koneksi.st.executeUpdate("insert into tbl_konsultan values (" + 0 + ",'" + tfKode.getText() + "','" + tfNama.getText() + "','" + tfJabatan.getText() + "','" + tfGolongan.getText() + "','" + tfTingkat.getText() + "')");
                JOptionPane.showMessageDialog(null, "Berhasil menyimpan");
                tampilKonsultan();
                aturTombol(false);
                kode();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "eror Simpan : " + e);
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnBaruActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBaruActionPerformed
        btnBaru.setEnabled(true);
        btnSimpan.setEnabled(true);
        
        bersih();
        kode();
    }//GEN-LAST:event_btnBaruActionPerformed

    private void btnEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditActionPerformed

        try {
            if (tfGolongan.getText().equals("") && tfTingkat.getText().equals("")) {
                tfGolongan.setText("-");
                tfTingkat.setText("-");
            }
            Model.Koneksi.st.executeUpdate("update tbl_konsultan set nama='" + tfNama.getText() + "',jabatan='" + tfJabatan.getText() + "',golongan='" + tfGolongan.getText() + "',tingkatan='" + tfTingkat.getText() + "' where kode_konsultan='" + tfKode.getText() + "'");
            JOptionPane.showMessageDialog(null, "Berhasil merubah ");
            tampilKonsultan();
            aturTombol(false);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Eror Hapus : " + e);
        }//blok Ubah

    }//GEN-LAST:event_btnEditActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
        try {
            Model.Koneksi.st.executeUpdate("delete from tbl_konsultan where kode_konsultan ='" + tfKode.getText() + "'  ");

            JOptionPane.showMessageDialog(null, "Berhasil menghapus ");
            tampilKonsultan();
            aturTombol(false);
            kode();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Eror Hapus : " + e);
        }//blok hapus
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(vKonsultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(vKonsultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(vKonsultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(vKonsultan.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                vKonsultan dialog = new vKonsultan(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBaru;
    private javax.swing.JButton btnEdit;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField tfGolongan;
    private javax.swing.JTextField tfJabatan;
    private javax.swing.JTextField tfKode;
    private javax.swing.JTextField tfNama;
    private javax.swing.JTextField tfTingkat;
    // End of variables declaration//GEN-END:variables

    private void bersih() {
        tfNama.setText("");
        tfGolongan.setText("");
        tfJabatan.setText("");
        tfTingkat.setText("");
        tfKode.setText("");

    }

    private void aturTombol(boolean b2) {
        btnBaru.setEnabled(true);
        btnSimpan.setEnabled(b2);
        btnEdit.setEnabled(b2);
        btnHapus.setEnabled(b2);
        tfKode.setEnabled(b2);

    }

    private boolean cekData() {
        boolean cek = true;
        if (tfNama.getText().equals("")) {
            cek = false;
        }
        if (tfJabatan.getText().equals("")) {
            cek = false;
        }
        if (cek == false) {
            JOptionPane.showMessageDialog(null, "Tolong Nama dan Jabatan Harus diIsi");
        }
        return cek;
    }

    private void headerTable() {
        model = new DefaultTableModel();
        model.addColumn("Kode");
        model.addColumn("Nama");
        model.addColumn("Jabatan");
        model.addColumn("Golongan");
        model.addColumn("Tingkatan");

        jTable1.setModel(model);
    }

    private void tampilKonsultan() {
        model.getDataVector().removeAllElements();
        try {
            ResultSet rs = Model.Koneksi.st.executeQuery("select * from tbl_konsultan");
            while (rs.next()) {
                Object[] data = new Object[6];
                data[0] = (rs.getString(2));
                data[1] = (rs.getString(3));
                data[2] = (rs.getString(4));
                data[3] = (rs.getString(5));
                data[4] = (rs.getString(6));
                model.addRow(data);
            }

//ini blok while
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "eror tampil : " + e);
        } //ini blok catch
        bersih();
    }

    private void kode() {
        System.out.println();
        String splits;
        for (int i = 0; i < model.getRowCount(); i++) {
            splits = jTable1.getValueAt(i, 0).toString();
            String[] parts = splits.split("-");

            if (Integer.parseInt(parts[1]) != i + 1) {
                System.out.println(Integer.parseInt(parts[1]));
                if (i < 10) {
                    tfKode.setText("k-0" + Integer.toString(i + 1));
                    break;
                } else {
                    tfKode.setText("k-" + Integer.toString(i + 1));
                    break;
                }
            }
            if ((model.getRowCount() + 1)<10) {
            tfKode.setText("k-0" + Integer.toString(model.getRowCount() + 1));
            }else{
            tfKode.setText("k-" + Integer.toString(model.getRowCount() + 1));    
            }

        }

    }

}
